Space-travelers-hub
yodit93/react-redux-group-project pull request #45
Opened 2023-04-13 18:10 UTC by yodit93

### In this project, we

- [ ] configured basic setup
- [ ] fetched data and update Redux store
- [ ] rendered UI:lists
- [ ] wrote actions and reducers for booking rockets/dragons and joining missions
- [ ] wrote actions and reducers for canceling rockets/dragons and leaving missions
- [ ] rendered UI: conditional components rendering
- [ ] rendered UI: My Profile section
- [ ] added tests

2023-04-13 18:24 UTC, youmari requested changes
Hi @yodit93 @Moses-chibuike , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Clean Design 
✔️ PRO PR
✔️ No linter error

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 18:30 UTC, yodit93 commented on src/__test__/Rocket.test.js
> +      <Provider store={store}>
Thanks, I will check it.

2023-04-13 19:20 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @yodit93, 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Indeed you did an exceptional but still, there is room for changes to complete this project. 💯


## Highlights 
✅State is updating according to requirements.
✅Design is well implemented.
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 19:26 UTC, yodit93 commented on src/Components/NavLink.js
> +export default NavLink;
Ok, I got it now, Thanks

2023-04-13 20:00 UTC, GedeonTS approved these changes
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi Team @yodit93 and @Moses-chibuike 

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
- No linter errors :+1: 
- Good use of Gitflow :+1: 
- All tests are passing :+1: 
## Optional suggestions :small_airplane: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 09:15 UTC, yodit93 commented on src/__test__/Rocket.test.js
> +      <Provider store={store}>
I didn't update the snapshot after changing some syntax on the files. That is why it is falling.

2023-04-15 09:17 UTC, yodit93 commented
Thank you!!!

2023-04-15 09:17 UTC, merged

2023-04-15 10:50 UTC, Moses-chibuike commented
> # STATUS: APPROVED 🎉 👏 🍾
> Hi Team @yodit93 and @Moses-chibuike
> 
> You are amazing 😃 👏 ! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> ![](https://camo.githubusercontent.com/395b3b21a125e95f2b70c16f35342677ad5350ec23bec5d6d9db1383f2c87427/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966) [ ![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966](https://camo.githubusercontent.com/395b3b21a125e95f2b70c16f35342677ad5350ec23bec5d6d9db1383f2c87427/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966) ](https://camo.githubusercontent.com/395b3b21a125e95f2b70c16f35342677ad5350ec23bec5d6d9db1383f2c87427/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966) [ ](https://camo.githubusercontent.com/395b3b21a125e95f2b70c16f35342677ad5350ec23bec5d6d9db1383f2c87427/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966)
> 
> ## Highlights 👏 🎩
> * No linter errors 👍
> * Good use of Gitflow 👍
> * All tests are passing 👍
> 
> ## Optional suggestions 🛩️
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thanks for approving